services:
  app:
    image: bitnami/laravel:latest
    ports:
      - '8001:8000'
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_DATABASE=erp
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=erp
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8080:80'
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=secret
      - UPLOAD_LIMIT=128M
      - MEMORY_LIMIT=256M
      - POST_MAX_SIZE=128M
      - MAX_EXECUTION_TIME=300
    depends_on:
      - db

volumes:
  dbdata:
